#ifndef __INTERRUPT_H__
#define __INTERRUPT_H__

#include "peripherals.h"

//INTERRUPT SOURCE
#define INTERRUPT_CORE0_GPIO_INTERRUPT_PRO_MAP_REG  (INTERRUPT_MATRIX_BASE + 0x0040)    //INTERRUPT FOR GPIO  (RW)
#define INTERRUPT_CORE0_TG_T0_INT_MAP_REG           (INTERRUPT_MATRIX_BASE + 0x80)      //INTERRUPT FOR TIMER GROUP
#define INTERRUPT_CORE0_TG_WDT_INT_MAP_REG          (INTERRUPT_MATRIX_BASE + 0x84)      //WATCHDOG TIMERGROUP INTERRUPT

//INTERRUPT STATUS REGISTER
#define INTERRUPT_CORE0_INTR_STATUS_0_REG           (INTERRUPT_MATRIX_BASE + 0xF8)
#define INTERRUPT_CORE0_INTR_STATUS_1_REG           (INTERRUPT_MATRIX_BASE + 0xFC)

//CLOCK REGISTER
#define INTERRUPT_CORE0_CLOCK_GATE_REG  (INTERRUPT_MATRIX_BASE + 0x100)

//CPU INTERRUPT REGISTERS
#define INTERRUPT_CORE0_CPU_INT_ENABLE_REG  (INTERRUPT_MATRIX_BASE + 0x104) //enable register for CPU interrupt
#define INTERRUPT_CORE0_CPU_INT_TYPE_REG    (INTERRUPT_MATRIX_BASE + 0x108)
#define INTERRUPT_CORE0_CPU_INT_CLEAR_REG   (INTERRUPT_MATRIX_BASE + 0x10C)
#define INTERRUPT_CORE0_CPU_INT_EIP_STATUS_REG  (INTERRUPT_MATRIX_BASE + 0x110)
#define INTERRUPT_CORE0_CPU_INT_PRI_n_REG (n)   (INTERRUPT_MATRIX_BASE + (0x118 + (n * 0x4)))
#define INTERRUPT_CORE0_CPU_INT_THRESH_REG  (INTERRUPT_MATRIX_BASE + 0x194)
/**
 * @brief Enable global trap in the CPU
 * and set the vector trap handler in Mvtec
 * This function is only called in the boot
 */
void trap_init();

void interrupt_init();
void handler_interrupt(unsigned int mcause);

#endif //__INTERRUPT_H__