#ifndef __PWM_H__
#define __PWM_H__

#include "peripherals.h"

//CONFIGURATION REG
#define LEDC_CH0_CONF0_REG  (LED_PWM_CONTROLLER_BASE + 0x0)
#define LEDC_CH0_CONF1_REG  (LED_PWM_CONTROLLER_BASE + 0xc)
#define LEDC_CH1_CONF0_REG  (LED_PWM_CONTROLLER_BASE + 0x14)
#define LEDC_CH1_CONF1_REG  (LED_PWM_CONTROLLER_BASE + 0x20)
#define LEDC_CH2_CONF0_REG  (LED_PWM_CONTROLLER_BASE + 0x28)
#define LEDC_CH2_CONF1_REG  (LED_PWM_CONTROLLER_BASE + 0x34)
#define LEDC_CH3_CONF0_REG  (LED_PWM_CONTROLLER_BASE + 0x3C)
#define LEDC_CH3_CONF1_REG  (LED_PWM_CONTROLLER_BASE + 0x48)
#define LEDC_CH4_CONF0_REG  (LED_PWM_CONTROLLER_BASE + 0x50)
#define LEDC_CH4_CONF1_REG  (LED_PWM_CONTROLLER_BASE + 0x5C)
#define LEDC_CH5_CONF0_REG  (LED_PWM_CONTROLLER_BASE + 0x64)
#define LEDC_CH5_CONF1_REG  (LED_PWM_CONTROLLER_BASE + 0x70)
#define LEDC_CONF_REG       (LED_PWM_CONTROLLER_BASE + 0xD0)

//HPOINT REG
#define LEDC_CH0_HPOINT_REG (LED_PWM_CONTROLLER_BASE + 0x4)
#define LEDC_CH1_HPOINT_REG (LED_PWM_CONTROLLER_BASE + 0x18)
#define LEDC_CH2_HPOINT_REG (LED_PWM_CONTROLLER_BASE + 0x2C)
#define LEDC_CH3_HPOINT_REG (LED_PWM_CONTROLLER_BASE + 0x40)
#define LEDC_CH4_HPOINT_REG (LED_PWM_CONTROLLER_BASE + 0x54)
#define LEDC_CH5_HPOINT_REG (LED_PWM_CONTROLLER_BASE + 0x68)

//DUTY CYCLE REG
#define LEDC_CH0_DUTY_REG   (LED_PWM_CONTROLLER_BASE + 0x8)
#define LEDC_CH0_DUTY_R_REG (LED_PWM_CONTROLLER_BASE + 0x10)
#define LEDC_CH1_DUTY_REG   (LED_PWM_CONTROLLER_BASE + 0x1C)
#define LEDC_CH1_DUTY_R_REG (LED_PWM_CONTROLLER_BASE + 0x24)
#define LEDC_CH2_DUTY_REG   (LED_PWM_CONTROLLER_BASE + 0x30)
#define LEDC_CH2_DUTY_R_REG (LED_PWM_CONTROLLER_BASE + 0x38)
#define LEDC_CH3_DUTY_REG   (LED_PWM_CONTROLLER_BASE + 0x44)
#define LEDC_CH3_DUTY_R_REG (LED_PWM_CONTROLLER_BASE + 0x4C)
#define LEDC_CH4_DUTY_REG   (LED_PWM_CONTROLLER_BASE + 0x58)
#define LEDC_CH4_DUTY_R_REG (LED_PWM_CONTROLLER_BASE + 0x60)
#define LEDC_CH5_DUTY_REG   (LED_PWM_CONTROLLER_BASE + 0x6C)
#define LEDC_CH5_DUTY_R_REG (LED_PWM_CONTROLLER_BASE + 0x74)

//TIMER REG
#define LEDC_TIMER0_CONF_REG    (LED_PWM_CONTROLLER_BASE + 0xA0)
#define LEDC_TIMER0_VALUE_REG   (LED_PWM_CONTROLLER_BASE + 0xA4)
#define LEDC_TIMER1_CONF_REG    (LED_PWM_CONTROLLER_BASE + 0xA8)
#define LEDC_TIMER1_VALUE_REG   (LED_PWM_CONTROLLER_BASE + 0xAC)
#define LEDC_TIMER2_CONF_REG    (LED_PWM_CONTROLLER_BASE + 0xB0)
#define LEDC_TIMER2_VALUE_REG   (LED_PWM_CONTROLLER_BASE + 0xB4)
#define LEDC_TIMER3_CONF_REG    (LED_PWM_CONTROLLER_BASE + 0xB8)
#define LEDC_TIMER3_VALUE_REG   (LED_PWM_CONTROLLER_BASE + 0xBC)

//INTERRUPT REG
#define LEDC_INT_RAW_REG        (LED_PWM_CONTROLLER_BASE + 0xC0)
#define LEDC_INT_ST_REG         (LED_PWM_CONTROLLER_BASE + 0xC4)
#define LEDC_INT_ENA_REG        (LED_PWM_CONTROLLER_BASE + 0xC8)
#define LEDC_INT_CLR_REG        (LED_PWM_CONTROLLER_BASE + 0xCC)

#endif //__PWM_H__