#ifndef __SYSREG_H__
#define __SYSREG_H__

#include "peripherals.h"



//PERIPHERAL CLOCK CONTROL REGISTERS
#define SYSTEM_CPU_PERI_CLK_EN_REG  (SYSTEM_REGISTERS_BASE + 0x0) //use for debug
#define SYSTEM_CPU_PERI_RST_EN_REG  (SYSTEM_REGISTERS_BASE + 0x4) //use for debug
#define SYSTEM_PERIP_CLK_EN0_REG    (SYSTEM_REGISTERS_BASE + 0x10)
#define SYSTEM_PERIP_CLK_EN1_REG    (SYSTEM_REGISTERS_BASE + 0x14)
#define SYSTEM_PERIP_RST_EN0_REG    (SYSTEM_REGISTERS_BASE + 0x18)
#define SYSTEM_PERIP_RST_EN1_REG    (SYSTEM_REGISTERS_BASE + 0x1C)
#define SYSTEM_CACHE_CONTROL_REG    (SYSTEM_REGISTERS_BASE + 0x40) //enable cache

//CLOCK CONFIGURATION REGISTERS
#define SYSTEM_CPU_PER_CONF_REG     (SYSTEM_REGISTERS_BASE + 0x8) //set the clock of the cpu
#define SYSTEM_SYSCLK_CONF_REG      (SYSTEM_REGISTERS_BASE + 0x58)

//CLOCK GATE CONTROL REGISTER
#define SYSTEM_CLOCK_GATE_REG       (SYSTEM_REGISTERS_BASE + 0x54)

//LOW POWER MANAGEMENT REG
#define SYSTEM_BT_LPCK_DIV_FRAC_REG     (SYSTEM_REGISTERS_BASE + 0x24)
#define SYSTEM_RTC_FASTMEM_CONFIG_REG   (SYSTEM_REGISTERS_BASE + 0x48)
#define SYSTEM_RTC_FASTMEM_CRC_REG      (SYSTEM_REGISTERS_BASE + 0x4C)

//SYSTEM AND MEMORY CONTROL REG
#define SYSTEM_RSA_DP_CTRL_REG      (SYSTEM_REGISTERS_BASE + 0x38)
#define SYSTEM_EXTERNAL_DEVICE_ENCRYPT_DECRYPT_CONTROL_REG  (SYSTEM_REGISTERS_BASE + 0x44)

//CPU INTERRUPT CONTROL REG
#define SYSTEM_CPU_INTR_FROM_CPU_0_REG  (SYSTEM_REGISTERS_BASE + 0x28)
#define SYSTEM_CPU_INTR_FROM_CPU_1_REG  (SYSTEM_REGISTERS_BASE + 0x2C)
#define SYSTEM_CPU_INTR_FROM_CPU_2_REG  (SYSTEM_REGISTERS_BASE + 0x30)
#define SYSTEM_CPU_INTR_FROM_CPU_3_REG  (SYSTEM_REGISTERS_BASE + 0x34)

//BIT POSITION FOR REGISTERS
#define SYSTEM_SOC_CLK_SEL      10
#define SYSTEM_PLL_FREQ_SEL     2
#define SYSTEM_CPUPERIOD_SEL    0

#define SYSTEM_ICACHE_CLK_ON    0
#define SYSTEM_DCACHE_CLK_ON    2

#define SYSTEM_TIMERS_CLK_EN        0
#define SYSTEM_LEDC_CLK_EN          11
#define SYSTEM_TIMERGROUP_CLK_EN    13
#define SYSTEM_TIMERGROUP1_CLK_EN   15
  

void sysreg_setup();

#endif //__SYSREG_H__