#ifndef __SYSREG_H__
#define __SYSREG_H__

#include "peripherals.h"

//PERIPHERAL CLOCK CONTROL REGISTERS
#define SYSTEM_CPU_PERI_CLK_EN_REG  (SYSTEM_REGISTERS_BASE + 0x0) //use for debug
#define SYSTEM_CPU_PERI_RST_EN_REG  (SYSTEM_REGISTERS_BASE + 0x4) //use for debug
#define SYSTEM_PERIP_CLK_EN0_REG    (SYSTEM_REGISTERS_BASE + 0x10)
#define SYSTEM_PERIP_CLK_EN1_REG    (SYSTEM_REGISTERS_BASE + 0x14)
#define SYSTEM_PERIP_RST_EN0_REG    (SYSTEM_REGISTERS_BASE + 0x18)
#define SYSTEM_PERIP_RST_EN1_REG    (SYSTEM_REGISTERS_BASE + 0x1C)
#define SYSTEM_CACHE_CONTROL_REG    (SYSTEM_REGISTERS_BASE + 0x40) //enable cache

//CLOCK CONFIGURATION REGISTERS
#define SYSTEM_CPU_PER_CONF_REG     (SYSTEM_REGISTERS_BASE + 0x8) //set the clock of the cpu
#define SYSTEM_SYSCLK_CONF_REG      (SYSTEM_REGISTERS_BASE + 0x58)

//CLOCK GATE CONTROL REGISTER
#define SYSTEM_CLOCK_GATE_REG       (SYSTEM_REGISTERS_BASE + 0x54)

//BIT POSITION FOR REGISTERS
#define SYSTEM_SOC_CLK_SEL      10
#define SYSTEM_PLL_FREQ_SEL     2
#define SYSTEM_CPUPERIOD_SEL    0

#define SYSTEM_ICACHE_CLK_ON    0
#define SYSTEM_DCACHE_CLK_ON    2

#define SYSTEM_TIMERS_CLK_EN        0
#define SYSTEM_LEDC_CLK_EN          11
#define SYSTEM_TIMERGROUP_CLK_EN    13
  

void sysreg_init();

#endif //__SYSREG_H__